name: .NET Core Backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: self-hosted  # For a list of available runner types, refer to
    steps:

    - name: Print current user
      run: whoami
    
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'


    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish -c Realease -o dist
