name: .NET Core Backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: self-hosted  # For a list of available runner types, refer to
    steps:
    - name: Print current user
      run: whoami

    - uses: actions/checkout@v4

  # IMPORTANT: REMOVE THE 'Install .NET Core' STEP THAT USES 'actions/setup-dotnet@v4' ENTIRELY.
  # It is trying to do an installation you don't need and can't perform this way.

    - name: Ensure Snap's .NET is available in PATH
      run: |
        # Add /snap/bin to the GitHub Actions PATH for this job.
        # It's likely already there by default on Ubuntu, but this ensures it.
        echo "/snap/bin" >> $GITHUB_PATH
        # You can also explicitly set DOTNET_ROOT if needed, but for snap it might not be directly /usr/share/dotnet
        # For snap, the SDKs are typically inside the snap's mounted filesystem.
        # Let's verify dotnet is found:
        dotnet --version
    
  
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build
